name: Release JavaScript actions
description: Release JavaScript actions
inputs:
  app_id:
    description: |
      GitHub App ID
    required: false
  app_private_key:
    description: |
      GitHub App Private Key
    required: false
  workflow:
    description: |
      How to handle changed workflow files.
      This input is used if `app_id` and `app_private_key` are specified.
      To commit workflow files, the permission `workflows:write` is required.
      The following values are available:
      1. allow - Grant `workflows:write` permission when creating an access token
      2. deny - Fail if workflow files are changed
      3. ignore - Ignore workflow files
    required: false
    default: allow
  files:
    description: |
      Files to be committed.
    required: false
  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: true
  commit_message:
    description: |
      Commit message
    required: false
    default: "commit changes"
  branch:
    description: |
      A Pushed branch.
      By default, GITHUB_HEAD_REF or GITHUB_REF_NAME is used.
    required: false
  parent_branch:
    description: |
      If a branch is newly created, the parent branch is used as the base branch.
      By default, the default branch is used.
    required: false
  repository:
    description: |
      A Pushed repository.
      By default, GITHUB_REPOSITORY is used.
    required: false
  root_dir:
    description: |
      The Git root directory for the files to commit.
    required: false
  fail_on_self_push:
    description: |
      Fail the action when a commit is pushed to the same repository and branch as the current workflow run.
      Set to 'false' to continue without failing (outputs still indicate the push).
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
