name: Create Commit By GitHub API
description: Commit changes by GitHub API
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: false
  commit_message:
    description: |
      Commit message
    required: false
    default: "commit changes"
  branch:
    description: |
      A Pushed branch.
      By default, GITHUB_HEAD_REF or GITHUB_REF_NAME is used.
    required: false
  parent_branch:
    description: |
      If a branch is newly created, the parent branch is used as the base branch.
      By default, the default branch is used.
    required: false
  repository:
    description: |
      A Pushed repository.
      By default, GITHUB_REPOSITORY is used.
    required: false
  app_id:
    description: |
      GitHub App ID
    required: false
  app_private_key:
    description: |
      GitHub App Private Key
    required: false
  files:
    description: |
      Files to commit. Unchanged files are ignored.
      To specify multiple files, separate them with a newline.
      By default, all modified and untracked files are committed.
      git ls-files --modified --others --exclude-standard
    required: false
  workflow:
    description: |
      How to handle changed workflow files.
      This input is used if `app_id` and `app_private_key` are specified.
      To commit workflow files, the permission `workflows:write` is required.
      The following values are available:
      1. allow - Grant `workflows:write` permission when creating an access token
      2. deny - Fail if workflow files are changed
      3. ignore - Ignore workflow files
    required: false
    default: allow
runs:
  using: composite
  steps:
    # Install suzuki-shunsuke/ghcp by aqua
    - run: echo "value=$GITHUB_ACTION_PATH/aqua/aqua.yaml" >> "$GITHUB_OUTPUT"
      id: aqua_config
      shell: bash
    - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.50.1
        skip_install_aqua: "true"
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}

    # List changed files
    - shell: bash
      id: files
      env:
        FILES: ${{ inputs.files }}
        WORKFLOW: ${{ inputs.workflow }}
      run: |
        echo 'permissions={"contents": "write"}' >> "$GITHUB_OUTPUT"
        if [ -z "$FILES" ]; then
          FILES=$(git ls-files --modified --others --exclude-standard)
          if [ -z "$FILES" ]; then
            echo "::notice:: No changes" >&2
            exit 0
          fi
        fi
        if [ "$WORKFLOW" = ignore ]; then
          echo "::notice:: Ignore workflow files" >&2
          FILES=$(echo "$FILES" | grep -vE '^\.github/workflows/')
        fi
        if [ "$WORKFLOW" = allow ]; then
          if echo "$FILES" | grep -qE '^\.github/workflows/'; then
            echo "::notice:: Grant workflows:write permission" >&2
            echo 'permissions={"contents": "write", "workflows": "write"}' >> "$GITHUB_OUTPUT"
          fi
        fi
        {
          echo 'files<<EOF'
          echo "$FILES"
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - shell: bash
      id: repo_name
      if: steps.files.outputs.files != ''
      run: |
        repo=${REPOSITORY:-$GITHUB_REPOSITORY}
        echo "value=${repo#*/}" >> "$GITHUB_OUTPUT"
      env:
        REPOSITORY: ${{ inputs.repository }}

    - uses: suzuki-shunsuke/github-token-action@350d7506222e3a0016491abe85b5c4dd475b67d1 # v0.2.1
      if: steps.files.outputs.files != ''
      id: token
      with:
        github_token: ${{inputs.github_token}}
        github_app_id: ${{inputs.app_id}}
        github_app_private_key: ${{inputs.app_private_key}}
        default_github_token: ${{github.token}}
        github_app_permissions: ${{steps.files.outputs.permissions}}
        github_app_repositories: >-
          [
            "${{steps.repo_name.outputs.value}}"
          ]

    - shell: bash
      if: steps.files.outputs.files != ''
      run: ghcp -v
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}

    # Commit changes
    - shell: bash
      if: steps.files.outputs.files != ''
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
        MESSAGE: ${{ inputs.commit_message }}
        BRANCH_NAME: ${{ inputs.branch }}
        PARENT_BRANCH: ${{ inputs.parent_branch }}
        REPOSITORY: ${{ inputs.repository }}
        FILES: ${{ steps.files.outputs.files }}
      run: |
        default_branch=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}
        branch=${BRANCH_NAME:-${default_branch}}
        repo=${REPOSITORY:-$GITHUB_REPOSITORY}
        tempfile=$(mktemp)
        if [ -n "$PARENT_BRANCH" ]; then
          echo "$FILES" | xargs ghcp commit -r "$repo" -D -m "$MESSAGE" -b "$branch" --parent "$PARENT_BRANCH" 2> >(tee -a "$tempfile" >&2)
        else
          echo "$FILES" | xargs ghcp commit -r "$repo" -D -m "$MESSAGE" -b "$branch" 2> >(tee -a "$tempfile" >&2)
        fi
        if grep -q "Nothing to commit" "$tempfile"; then
          exit 0
        fi
        if [ "$repo" != "$GITHUB_REPOSITORY" ] || [ "$branch" != "$default_branch"  ]; then
          exit 0
        fi
        exit 1
