name: Create Commit By GitHub API
description: Commit changes by GitHub API
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: false
  commit_message:
    description: |
      Commit message
    required: false
    default: "commit changes"
  branch:
    description: |
      A Pushed branch.
      By default, GITHUB_HEAD_REF or GITHUB_REF_NAME is used.
    required: false
  parent_branch:
    description: |
      If a branch is newly created, the parent branch is used as the base branch.
      By default, the default branch is used.
    required: false
  repository:
    description: |
      A Pushed repository.
      By default, GITHUB_REPOSITORY is used.
    required: false
  app_id:
    description: |
      GitHub App ID
    required: false
  app_private_key:
    description: |
      GitHub App Private Key
    required: false
  files:
    description: |
      Files to commit. Unchanged files are ignored.
      To specify multiple files, separate them with a newline.
      By default, all modified and untracked files are committed.
      git ls-files --modified --others --exclude-standard
    required: false
  workflow:
    description: |
      How to handle changed workflow files.
      This input is used if `app_id` and `app_private_key` are specified.
      To commit workflow files, the permission `workflows:write` is required.
      The following values are available:
      1. allow - Grant `workflows:write` permission when creating an access token
      2. deny - Fail if workflow files are changed
      3. ignore - Ignore workflow files
    required: false
    default: allow
outputs:
  pushed:
    description: |
      Whether the commit was pushed.
      If the commit is not pushed, it means that there are no changes to commit.
    value: ${{ steps.files.outputs.files != '' && steps.commit.outputs.pushed == 'true' }}
  sha:
    description: |
      Full length commit SHA to be pushed.
    value: ${{steps.commit.outputs.sha}}
runs:
  using: composite
  steps:
    # List changed files
    - shell: bash
      id: files
      env:
        FILES: ${{ inputs.files }}
        WORKFLOW: ${{ inputs.workflow }}
      run: |
        echo 'permissions={"contents": "write"}' >> "$GITHUB_OUTPUT"
        if [ -z "$FILES" ]; then
          FILES=$(git ls-files --modified --others --exclude-standard)
          if [ -z "$FILES" ]; then
            echo "::notice:: No changes" >&2
            exit 0
          fi
        fi
        if [ "$WORKFLOW" = ignore ]; then
          echo "::notice:: Ignore workflow files" >&2
          FILES=$(echo "$FILES" | grep -vE '^\.github/workflows/')
        fi
        if [ "$WORKFLOW" = allow ]; then
          if echo "$FILES" | grep -qE '^\.github/workflows/'; then
            echo "::notice:: Grant workflows:write permission" >&2
            echo 'permissions={"contents": "write", "workflows": "write"}' >> "$GITHUB_OUTPUT"
          fi
        fi
        {
          echo 'files<<EOF'
          echo "$FILES"
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - shell: bash
      id: repo_name
      if: steps.files.outputs.files != ''
      run: |
        repo=${REPOSITORY:-$GITHUB_REPOSITORY}
        echo "value=${repo#*/}" >> "$GITHUB_OUTPUT"
      env:
        REPOSITORY: ${{ inputs.repository }}

    - uses: suzuki-shunsuke/github-token-action@350d7506222e3a0016491abe85b5c4dd475b67d1 # v0.2.1
      if: steps.files.outputs.files != ''
      id: token
      with:
        github_token: ${{inputs.github_token}}
        github_app_id: ${{inputs.app_id}}
        github_app_private_key: ${{inputs.app_private_key}}
        default_github_token: ${{github.token}}
        github_app_permissions: ${{steps.files.outputs.permissions}}
        github_app_repositories: >-
          [
            "${{steps.repo_name.outputs.value}}"
          ]

    - uses: suzuki-shunsuke/commit-action/js@4b469e6c0df5c7fdff25ebf8d4cb65ab2bde8197
      id: commit
      with:
        github_token: ${{ steps.token.outputs.token }}
        repository: ${{ inputs.repository }}
        branch: ${{ inputs.branch }}
        files: ${{ steps.files.outputs.files }}
        commit_message: ${{ inputs.commit_message }}
        parent_branch: ${{ inputs.parent_branch }}
