name: Create Commit By GitHub API
description: Commit changes by GitHub API
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: false
  commit_message:
    description: |
      Commit message
    required: false
    default: "commit changes"
  branch:
    description: |
      A Pushed branch.
      By default, GITHUB_HEAD_REF or GITHUB_REF_NAME is used.
    required: false
  repository:
    description: |
      A Pushed repository.
      By default, GITHUB_REPOSITORY is used.
    required: false
  app_id:
    description: |
      GitHub App ID
    required: false
  app_private_key:
    description: |
      GitHub App Private Key
    required: false
  files:
    description: |
      Files to commit. Unchanged files are ignored.
      By default, all modified and untracked files are committed.
      git ls-files --modified --others --exclude-standard
    required: false
runs:
  using: composite
  steps:
    # Install suzuki-shunsuke/ghcp by aqua
    - run: echo "value=$GITHUB_ACTION_PATH/aqua/aqua.yaml" >> "$GITHUB_OUTPUT"
      id: aqua_config
      shell: bash
    - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
      with:
        aqua_version: v2.43.2
        skip_install_aqua: "true"
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}

    - shell: bash
      id: repo_name
      run: |
        repo=${REPOSITORY:-$GITHUB_REPOSITORY}
        echo "value=${repo#*/}" >> "$GITHUB_OUTPUT"
      env:
        REPOSITORY: ${{ inputs.repository }}

    - uses: suzuki-shunsuke/github-token-action@350d7506222e3a0016491abe85b5c4dd475b67d1 # v0.2.1
      id: token
      with:
        github_token: ${{inputs.github_token}}
        github_app_id: ${{inputs.app_id}}
        github_app_private_key: ${{inputs.app_private_key}}
        default_github_token: ${{github.token}}
        github_app_permissions: >-
          {
            "contents": "write"
          }
        github_app_repositories: >-
          [
            "${{steps.repo_name.outputs.value}}"
          ]

    - shell: bash
      run: ghcp -v
      env:
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}

    # List changed files
    # Commit changes
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
        MESSAGE: ${{ inputs.commit_message }}
        BRANCH_NAME: ${{ inputs.branch }}
        REPOSITORY: ${{ inputs.repository }}
        FILES: ${{ inputs.files }}
      run: |
        if [ -z "$FILES" ]; then
          FILES=$(git ls-files --modified --others --exclude-standard)
          if [ -z "$FILES" ]; then
            echo "No changes" >&2
            exit 0
          fi
        fi
        branch=${BRANCH_NAME:-${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}}
        repo=${REPOSITORY:-$GITHUB_REPOSITORY}
        echo "$FILES" | xargs ghcp commit -r "$repo" -D -m "$MESSAGE" -b "$branch"
        exit 1
