name: Create Commit By GitHub API
description: Commit changes by GitHub API
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: false
  app_id:
    description: |
      GitHub App ID
    required: false
  app_private_key:
    description: |
      GitHub App Private Key
    required: false
  commit_message:
    description: |
      Commit message
    required: false
    default: "commit changes"
  branch:
    description: |
      A Pushed branch.
      By default, GITHUB_HEAD_REF or GITHUB_REF_NAME is used.
    required: false
  parent_branch:
    description: |
      If a branch is newly created, the parent branch is used as the base branch.
      By default, the default branch is used.
    required: false
  repository:
    description: |
      A Pushed repository.
      By default, GITHUB_REPOSITORY is used.
    required: false
  root_dir:
    description: |
      The Git root directory for the files to commit.
    required: false
  files:
    description: |
      Files to commit. Unchanged files are ignored.
      To specify multiple files, separate them with a newline.
      By default, all modified and untracked files are committed.
      git ls-files --modified --others --exclude-standard
    required: false
  workflow:
    description: |
      How to handle changed workflow files.
      This input is used if `app_id` and `app_private_key` are specified.
      To commit workflow files, the permission `workflows:write` is required.
      The following values are available:
      1. allow - Grant `workflows:write` permission when creating an access token
      2. deny - Fail if workflow files are changed
      3. ignore - Ignore workflow files
    required: false
    default: allow
  fail_on_self_push:
    description: |
      If true (default), the action fails when it pushes a commit to the same repo/branch as the current workflow run.
      Set to false to avoid failing and check outputs instead.
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
