---
name: Release (workflow call)
on:
  workflow_call:
    inputs:
      version:
        description: Version
        required: true
        type: string
      pr:
        description: Pull Request Number
        required: false
        type: string
      is_comment:
        description: If the comment is posted
        required: false
        default: false
        type: boolean
jobs:
  create-pr-branch:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - run: gh pr checkout "$PR"
        if: inputs.pr != ''
        env:
          GITHUB_TOKEN: ${{github.token}}
          PR: ${{inputs.pr}}
      - run: npm ci
        working-directory: js
      - run: npm run build
        working-directory: js

      - uses: suzuki-shunsuke/release-js-action@23ab6d1545309c79664bc0e9aea74daf27339193 # v0.1.8-2
        with:
          version: ${{inputs.version}}
          pr: ${{inputs.pr}}
          is_comment: ${{inputs.is_comment}}
